language: c
compiler: gcc
before_install:
  - python -m pip install -U pip --user cpp-coveralls
  - python -m pip install -U pip --user pyyaml
script:
  - chmod +x configure
  - ./configure --enable-gcov
  - gcc -o bin/open-with-cmd.exe src/main.c
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
