language: c
compiler: gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - raymelon/open-with-cmd/configure --enable-gcov && make && make check
  - gcc -o bin/open-with-cmd.exe src/main.c
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
